routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DataController;
use App\Http\Controllers\Admin\DashboardAdminController;
// use App\Http\Controllers\Admin\RepositoriAdminController;
use App\Http\Controllers\Admin\DataUserAdminController;
use App\Http\Controllers\Admin\DataKegiatanAdminController;
use App\Http\Controllers\Admin\DataKaryawanAdminController;
use App\Http\Controllers\Admin\DataStatusKegiatanAdminController;
use App\Http\Controllers\Admin\DataInformasiAdminController;
use App\Http\Controllers\Admin\DataLaporanAdminController;
// use App\Http\Controllers\User\DashboardController;
// use App\Http\Controllers\User\RepositoriController;
use App\Http\Controllers\User\DashboardUserController;
// use App\Http\Controllers\PendaftaranController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/fcm', [App\Http\Controllers\NotifController::class, 'index']);
Route::get('/send', [App\Http\Controllers\NotifController::class, 'sendNotification']);

Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login-post');
Route::get('/regist', [AuthController::class, 'regist'])->name('registrasi');
Route::post('registrasi', [AuthController::class, 'registrasi'])->name('registrasi-user');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
Route::get('pendaftaran', [PendaftaranController::class, 'index'])->name('pendaftaran');


//middeware
Route::group(['middleware' => ['cekLogin']], function () {

    // Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    // Route::get('repositori', [DataController::class, 'index'])->name('repositori');
    // Route::post('tambah_data', [DataController::class, 'tambah'])->name('tambah_data');

    Route::get('upload', [DataController::class, 'file'])->name('file');
    Route::post('upload', [DataController::class, 'upload'])->name('upload');


    Route::group(['middleware' => ['cekAdmin']], function () {
        // Admin
        Route::get('/dashboard_admin', [DashboardAdminController::class, 'index'])->name('dashboard_admin');
        Route::get('/profile_admin', [DashboardAdminController::class, 'profile'])->name('profile.admin');
        Route::put('/ubah.profile.admin/{id}', [DashboardAdminController::class, 'ubahProfile'])->name('ubah.profile.admin');
        Route::resource('user', DataUserAdminController::class);
        Route::resource('karyawan', DataKaryawanAdminController::class);
        Route::resource('kegiatan', DataKegiatanAdminController::class);
        Route::resource('status_kegiatan', DataStatusKegiatanAdminController::class);
        Route::resource('informasi', DataInformasiAdminController::class);
        Route::resource('laporan', DataLaporanAdminController::class);
        Route::post('laporan/cari', [DataLaporanAdminController::class, 'cari'])->name('laporan.cari');
        Route::get('cetak_pdf/{awal}/{akhir}', [DataLaporanAdminController::class, 'cetak_pdf'])->name('cetak.pdf');
    });

    Route::group(['middleware' => ['cekUser']], function () {
        // User
        Route::get('/dashboard', [DashboardUserController::class, 'index'])->name('dashboard');
        Route::get('/pekerja', [DashboardUserController::class, 'pekerja'])->name('pekerja');
        Route::get('/informasi-pekerja', [DashboardUserController::class, 'informasi'])->name('informasi-pekerja');
        Route::get('/agenda', [DashboardUserController::class, 'kegiatan'])->name('agenda');
        Route::get('/cetak-kegiatan', [DashboardUserController::class, 'cetakKegiatan'])->name('cetakKegiatan');
        Route::get('/cetak-kegiatan/{id}', [DashboardUserController::class, 'cetakKegiatanId'])->name('cetakKegiatanId');
        // Route::get('/detail/agenda', [DashboardUserController::class, 'detailAgenda'])->name('detail-agenda');
        Route::get('/profil', [DashboardUserController::class, 'profil'])->name('profil');
        Route::put('/ubah.profile/{id}', [DashboardUserController::class, 'ubahProfile'])->name('ubah.profile');

        //repositori
        Route::get('/repositori', [RepositoriController::class, 'index'])->name('repositori');
        Route::get('/tambah_data', [RepositoriController::class, 'tambah'])->name('tambah');
        Route::post('/insert_data', [RepositoriController::class, 'insert'])->name('insert');
        Route::get('repositori_ubah/{id}', [RepositoriController::class, 'ubah']);
        Route::post('repositori_edit/{id}', [RepositoriController::class, 'edit'])->name('repositori_edit');
        Route::get('repositori_hapus/{id}', [RepositoriController::class, 'hapus']);
    });
});

resources/views/template_admin/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>@yield('title')</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!-- CSS Libraries -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap4.min.css">


    <!-- Template CSS -->
    <link rel="stylesheet" href="../assets/css/style.css">
    <link rel="stylesheet" href="../assets/css/components.css">
</head>

<body>
    <div id="app">
        <div class="main-wrapper">
            <div class="navbar-bg "></div>
            @include('template_admin.topbar')
            @include('template_admin.sidebar')

            <!-- Main Content -->
            <div class="main-content">
                @include('sweetalert::alert')
                @yield('content')
            </div>
            {{-- <footer class="main-footer">
        <div class="footer-left">
          Copyright &copy; 2018 <div class="bullet"></div> Design By <a href="https://nauval.in/">Muhamad Nauval Azhar</a>
        </div>
        <div class="footer-right">
          2.3.0
        </div>
      </footer> --}}
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal Upload Fele</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="">
                        <div class="form-group">
                            <label for="">Nama</label>
                            <input type="file" value="" class="form-control">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    <!-- General JS Scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="../assets/js/stisla.js"></script>

    <!-- JS Libraies -->
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>

    <!-- Template JS File -->
    <script src="../assets/js/scripts.js"></script>
    <script src="../assets/js/custom.js"></script>

    <script>
        $(document).ready(function() {
            $('#myTable').DataTable();
        });
    </script>

    <!-- Page Specific JS File -->
</body>

</html>

resources/views/template_admin/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="index.html">Admin</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">A</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>
            <li class="{{ request()->is('dashboard_admin') ? 'active' : '' }}"><a class="nav-link"
                    href="{{ route('dashboard_admin') }}"><i class="fas fa-fire"></i>
                    <span>Dashboard</span></a></li>
            <li class="menu-header">Starter</li>
            <li class="{{ request()->is('karyawan*') ? 'active' : '' }}"><a class="nav-link"
                    href="{{ route('karyawan.index') }}"><i class="fas fa-users"></i>
                    <span>Data Karyawan</span></a></li>
            <li class="{{ request()->is('kegiatan*') ? 'active' : '' }}"><a class="nav-link"
                    href="{{ route('kegiatan.index') }}"><i class="fas fa-calendar-alt"></i>
                    <span>Data Kegiatan</span></a></li>
            {{-- <li class="{{ request()->is('status_kegiata*') ? 'active' : '' }}"><a class="nav-link"
                    href="{{ route('status_kegiatan.index') }}"><i class="fas fa-university"></i>
                    <span>Data Status Kegiatan</span></a></li> --}}
            <li class="{{ request()->is('informasi*') ? 'active' : '' }}"><a class="nav-link"
                    href="{{ route('informasi.index') }}"><i class="far fa-clipboard"></i>
                    <span>Data Informasi</span></a></li>
            <li class="{{ request()->is('user*') ? 'active' : '' }}"><a class="nav-link"
                    href="{{ route('user.index') }}"><i class="fas fa-user"></i>
                    <span>Data User</span></a></li>
            <li class="{{ request()->is('laporan*') ? 'active' : '' }}"><a class="nav-link"
                    href="{{ route('laporan.index') }}"><i class="fas fa-file"></i>
                    <span>Laporan</span></a></li>
            {{-- <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="fas fa-american-sign-language-interpreting"></i> <span>Kerjasama</span></a>
            <ul class="dropdown-menu">
              <li><a href="{{ route('repositori_admin') }}">Repositori</a></li>
              <li><a href="gmaps-draggable-marker.html">Program</a></li>
              <li><a href="gmaps-geocoding.html">Mitra</a></li>
            </ul> --}}
        </ul>

        <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
            <a href="{{ route('logout') }}" class="btn btn-primary btn-lg btn-block btn-icon-split">
                <i class="fas fa-sign-out-alt"></i> Logout
            </a>
        </div>
    </aside>
</div>

resources/views/template_admin/topbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i
                        class="fas fa-search"></i></a></li>
        </ul>
    </form>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown"><a href="#" data-toggle="dropdown"
                class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ url(Storage::url(Auth::user()->foto)) }}" class="rounded-circle mr-1" style="width: 40px;height:40px;">
                <div class="d-sm-none d-lg-inline-block">Hi, {{ Auth::user()->name }}</div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="{{ route('profile.admin') }}" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Profile
                </a>
                <div class="dropdown-divider"></div>
                <a href="{{ url('logout') }}" class="dropdown-item has-icon text-danger">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            </div>
        </li>
    </ul>
</nav>