routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DataController;
use App\Http\Controllers\Admin\DashboardAdminController;
// use App\Http\Controllers\Admin\RepositoriAdminController;
use App\Http\Controllers\Admin\DataUserAdminController;
use App\Http\Controllers\Admin\DataKegiatanAdminController;
use App\Http\Controllers\Admin\DataKaryawanAdminController;
use App\Http\Controllers\Admin\DataStatusKegiatanAdminController;
use App\Http\Controllers\Admin\DataInformasiAdminController;
use App\Http\Controllers\Admin\DataLaporanAdminController;
// use App\Http\Controllers\User\DashboardController;
// use App\Http\Controllers\User\RepositoriController;
use App\Http\Controllers\User\DashboardUserController;
// use App\Http\Controllers\PendaftaranController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/fcm', [App\Http\Controllers\NotifController::class, 'index']);
Route::get('/send', [App\Http\Controllers\NotifController::class, 'sendNotification']);

Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login-post');
Route::get('/regist', [AuthController::class, 'regist'])->name('registrasi');
Route::post('registrasi', [AuthController::class, 'registrasi'])->name('registrasi-user');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
Route::get('pendaftaran', [PendaftaranController::class, 'index'])->name('pendaftaran');


//middeware
Route::group(['middleware' => ['cekLogin']], function () {

    // Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    // Route::get('repositori', [DataController::class, 'index'])->name('repositori');
    // Route::post('tambah_data', [DataController::class, 'tambah'])->name('tambah_data');

    Route::get('upload', [DataController::class, 'file'])->name('file');
    Route::post('upload', [DataController::class, 'upload'])->name('upload');


    Route::group(['middleware' => ['cekAdmin']], function () {
        // Admin
        Route::get('/dashboard_admin', [DashboardAdminController::class, 'index'])->name('dashboard_admin');
        Route::get('/profile_admin', [DashboardAdminController::class, 'profile'])->name('profile.admin');
        Route::put('/ubah.profile.admin/{id}', [DashboardAdminController::class, 'ubahProfile'])->name('ubah.profile.admin');
        Route::resource('user', DataUserAdminController::class);
        Route::resource('karyawan', DataKaryawanAdminController::class);
        Route::resource('kegiatan', DataKegiatanAdminController::class);
        Route::resource('status_kegiatan', DataStatusKegiatanAdminController::class);
        Route::resource('informasi', DataInformasiAdminController::class);
        Route::resource('laporan', DataLaporanAdminController::class);
        Route::post('laporan/cari', [DataLaporanAdminController::class, 'cari'])->name('laporan.cari');
        Route::get('cetak_pdf/{awal}/{akhir}', [DataLaporanAdminController::class, 'cetak_pdf'])->name('cetak.pdf');
    });

    Route::group(['middleware' => ['cekUser']], function () {
        // User
        Route::get('/dashboard', [DashboardUserController::class, 'index'])->name('dashboard');
        Route::get('/pekerja', [DashboardUserController::class, 'pekerja'])->name('pekerja');
        Route::get('/informasi-pekerja', [DashboardUserController::class, 'informasi'])->name('informasi-pekerja');
        Route::get('/agenda', [DashboardUserController::class, 'kegiatan'])->name('agenda');
        Route::get('/cetak-kegiatan', [DashboardUserController::class, 'cetakKegiatan'])->name('cetakKegiatan');
        Route::get('/cetak-kegiatan/{id}', [DashboardUserController::class, 'cetakKegiatanId'])->name('cetakKegiatanId');
        // Route::get('/detail/agenda', [DashboardUserController::class, 'detailAgenda'])->name('detail-agenda');
        Route::get('/profil', [DashboardUserController::class, 'profil'])->name('profil');
        Route::put('/ubah.profile/{id}', [DashboardUserController::class, 'ubahProfile'])->name('ubah.profile');

        //repositori
        Route::get('/repositori', [RepositoriController::class, 'index'])->name('repositori');
        Route::get('/tambah_data', [RepositoriController::class, 'tambah'])->name('tambah');
        Route::post('/insert_data', [RepositoriController::class, 'insert'])->name('insert');
        Route::get('repositori_ubah/{id}', [RepositoriController::class, 'ubah']);
        Route::post('repositori_edit/{id}', [RepositoriController::class, 'edit'])->name('repositori_edit');
        Route::get('repositori_hapus/{id}', [RepositoriController::class, 'hapus']);
    });
});

resources/views/admin/data_informasi/index.blade.php
@extends('template_admin.app')

@section('title', 'Data Informasi')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Data Informasi</h1>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalTambah">Tambah Data</a>
                    <hr>
                    @if (session('informasi'))
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <strong>{{ session('informasi') }}</strong>
                        </div>
                    @endif
                    <table class="table table-bordered table-striped" id="myTable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Informasi</th>
                                <th>Jenis Informasi</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (!empty($informasis))
                                @foreach ($informasis as $no => $item)
                                    <tr>
                                        <td>{{ $no + 1 }}</td>
                                        <td>{{ $item->informasi }}</td>
                                        <td>{{ $item->jenis_informasi }}</td>
                                        <td>{{ $item->status }}</td>
                                        <td>
                                            <form action="{{ route('informasi.destroy', $item->id) }}" method="post">
                                                @method('DELETE')
                                                @csrf
                                                <a href="#" data-toggle="modal"
                                                    data-target="#exampleModalEdit{{ $item->id }}"
                                                    class="btn btn-sm btn-info"><i class="fas fa-edit"></i></a>
                                                <button type="submit" class="btn btn-danger btn-sm"><i
                                                        class="fas fa-trash"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

    <!-- Button trigger modal -->
    {{-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Launch demo modal
    </button> --}}

    <!-- Modal Tambah-->
    <div class="modal fade" id="exampleModalTambah" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Tambah Data</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('informasi.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="">Informasi</label>
                            <textarea name="informasi" id="" cols="30" rows="10" class="form-control"></textarea>
                            @error('informasi')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Jenis Informasi</label>
                            <select name="jenis_informasi" id="" class="form-control">
                                <option value=" ">-- PIlihan --</option>
                                <option value="Umum">Umum</option>
                                <option value="Khusus">Khusus</option>
                            </select>
                            @error('jenis_informasi')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Status</label>
                            <select name="status" id="" class="form-control">
                                <option value=" ">-- PIlihan --</option>
                                <option value="1">Aktif</option>
                                <option value="2">Tidak Aktif</option>
                            </select>
                            @error('jenis_informasi')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="float-right">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Keluar</button>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Edit-->
    @foreach ($informasis as $item)
        <div class="modal fade" id="exampleModalEdit{{ $item->id }}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ubah Data</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('informasi.update', $item->id) }}" method="post">
                            @method('PUT')
                            @csrf
                            <div class="form-group">
                                <label for="">Informasi</label>
                                <textarea name="informasi" class="form-control" rows="10">{{ $item->informasi }}</textarea>
                                @error('informasi')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="">Jenis Informasi</label>
                                <select name="jenis_informasi" id="" class="form-control">
                                    <option value="Umum" {{ $item->jenis_informasi == 'Umum' ? 'selected' : '' }}>Umum
                                    </option>
                                    <option value="Khusus" {{ $item->jenis_informasi == 'Khusus' ? 'selected' : '' }}>
                                        Khusus</option>
                                </select>
                                @error('jenis_informasi')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="">Status</label>
                                <select name="status" id="" class="form-control">
                                    <option value="1" {{ $item->status == '1' ? 'selected' : '' }}>
                                        Aktif</option>
                                    <option value="2" {{ $item->status == '2' ? 'selected' : '' }}>Tidak Aktif
                                    </option>
                                </select>
                                @error('status')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="float-right">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Keluar</button>
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
@endsection